const ACTION_TYPES = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  VERIFY_AUTH: 'VERIFY_AUTH',
  VERIFY_PROFILE: 'VERIFY_PROFILE',
  FILL_PROFILE: 'FILL_PROFILE',
};

export default ACTION_TYPES;
